_target_: torch.optim.AdamW
param_groups:
  - name: backbone
    lr: 0.0001
    momentum: 0.8
    weight_decay: 0.0001
    betas: [0.9, 0.999]
  - name: head
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
    betas: [0.9, 0.999]