_target_: torch.optim.AdamW
param_groups:
  - name: backbone
    lr: 0.0001
    weight_decay: 0.0001
    betas: [0.9, 0.999]
    amsgrad: false
    eps: 1e-8
  - name: head
    lr: 0.001
    weight_decay: 0.0005
    betas: [0.9, 0.999]
    msgrad: false
    eps: 1e-8