name: cs7643-project
channels:
  - defaults
dependencies:
  # - python==3.8.10
  - python>=3.12,<3.13
  - matplotlib
  - jupyter
  - pip
  - pip:
      - opencv-python
      - scikit-learn
      - rasterio
      - notebook
      - numpy
      - pycocotools
      - Pillow
      - ultralytics
      - hydra-core
      - omegaconf
      - shapely
      - tqdm
      - rich
