name: cs7643-project
channels:
  - defaults
dependencies:
  # - python==3.8.10
  - python>=3.10,<3.11
  - matplotlib
  - tqdm
  - jupyter
  - pip
  - pip:
    - opencv-python
    - scikit-learn
    - rasterio
    - notebook
    - numpy
    - pycocotools
    - Pillow
    - ultralytics
    - hydra-core
    - omegaconf
    - shapely