defaults:
  - _self_ 
  - optimizer: sgd
  - scheduler: steplr

hydra:
  hydra_logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      simple:
        format: "%(asctime)s %(levelname)-7s %(name)s: %(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    root:
      handlers: [console]
      level: INFO
model:
  detection_threshold: 0.2
  nms_threshold: 0.7
  max_detections_per_img: 200
data:
  num_classes: 16 # for Dotav1.5 this has to be 16

training:
  batch_size: 4
  epochs: 100
  num_workers: 8
  log_every_n_steps: 10
  save_every_n_steps: 100
  save_dir: ./checkpoints
  output_dir: ./outputs
  precision: 16