defaults:
  - _self_ 
  - optimizer: sgd2
  - scheduler: steplr

hydra:
  hydra_logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      simple:
        format: "%(asctime)s %(levelname)-7s %(name)s: %(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    root:
      handlers: [console]
      level: INFO
data:
  num_classes: null # for Dotav1.5 this has to be 16

training:
  batch_size: 4
  epochs: 200
  num_workers: 8
  log_every_n_steps: 1
  save_every_n_steps: 50
  save_dir: ./checkpoints
  output_dir: ./outputs
  precision: 32
  resume_from_checkpoint: /root/dev/CS-7643-Final-Project/src/checkpoints/dota-epoch=99-map_50=0.456.ckpt
  unfreeze_epoch: 100
  overfit_batches: 0