defaults:
  - _self_ 
  - optimizer: adamw
  - scheduler: steplr

hydra:
  hydra_logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      simple:
        format: "%(asctime)s %(levelname)-7s %(name)s: %(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    root:
      handlers: [console]
      level: INFO

model:
  backbone: mobilenet # either mobilenet or resnet
  num_classes: 16 # for Dotav1.5 this has to be 16

training:
  batch_size: 4
  epochs: 20
  loss:
    reg_max: 16  # from the ultralytics repo:  DFL channels (ch[0] // 16 to scale 4/8/12/16/20 for n/s/m/l/x)